export const PROFILE_LANGUAGES = [
  "English",
  "Chinese",
  "Hindi",
  "Portuguese",
  "Spanish",
  "Arabic",
  "Bulgarian",
  "French",
  "Russian",
];

export const PROFILE_INTERESTS = [
  "History",
  "Art",
  "Booking",
  "Code",
  "Content",
  "Entertainment",
  "Translator",
  "Health",
  "Music",
  "Books",
  "Toys",
  "Handbags",
  "Mobile Phones",
  "Games",
  "Kitchen Ware",
  "Baby Care",
  "Household Appliances",
  "Fitness Equipment",
  "Sports Goods",
  "Home Decor",
  "Computer Accessories",
];
